# Generated by Django 3.2.7 on 2021-09-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_date_joined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='date_joined',
        ),
    ]
