# Generated by Django 3.2.7 on 2021-10-03 19:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('crudModelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('id_checkin', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_checkin', models.DateField()),
                ('lista_checkeo', models.CharField(max_length=100, null=True)),
                ('documento_pdf', models.FileField(null=True, upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('id_checkout', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fecha_checkout', models.DateField()),
                ('costo_reparacion', models.IntegerField(null=True)),
                ('valor_servicio_extra', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sv_Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('valor_tour', models.IntegerField(default=0)),
                ('fecha_registro_tour', models.DateField(null=True)),
                ('descripcion_tour', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Sv_Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_chofer', models.CharField(max_length=30, null=True)),
                ('apellido_chofer', models.CharField(max_length=30, null=True)),
                ('patente_vehiculo', models.CharField(max_length=10, null=True)),
                ('fecha_ida', models.DateField(null=True)),
                ('fecha_vuelta', models.DateField(null=True)),
                ('direccion_inicio', models.CharField(max_length=50, null=True)),
                ('valor_transporte', models.IntegerField(default=0)),
                ('fecha_solicitud', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('valor_total', models.IntegerField(default=0)),
                ('is_pago_anticipo', models.BooleanField(default=False)),
                ('is_pago_checkin', models.BooleanField(default=False)),
                ('is_pago_checkout', models.BooleanField(default=False)),
                ('id_check_in', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.checkin')),
                ('id_check_out', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.checkout')),
                ('id_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('id_departamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.departamento')),
            ],
        ),
        migrations.CreateModel(
            name='PersonaExtra',
            fields=[
                ('rut', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=30, null=True)),
                ('apellido', models.CharField(max_length=30, null=True)),
                ('id_reserva', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.reserva')),
            ],
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_tour',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.sv_transporte'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_transporte',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.sv_tour'),
        ),
    ]
