# Generated by Django 3.2.7 on 2021-10-01 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('crudModelos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('check_in', models.DateTimeField()),
                ('check_out', models.DateTimeField()),
                ('valor_total', models.IntegerField(default=0)),
                ('primer_pago_anticipo', models.IntegerField(default=0)),
                ('segundo_pago_checkin', models.IntegerField(default=0)),
                ('tercer_pago_checkout', models.IntegerField(default=0)),
                ('is_primerPago', models.BooleanField(default=False)),
                ('is_segundoPago', models.BooleanField(default=False)),
                ('is_tercerPago', models.BooleanField(default=False)),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cliente')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crudModelos.departamento')),
            ],
        ),
    ]
