# Generated by Django 3.2.7 on 2021-10-07 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='is_tour',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='is_transporte',
            field=models.BooleanField(default=False),
        ),
    ]
