# Generated by Django 3.2.7 on 2021-10-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='por_pagar',
            field=models.IntegerField(default=0),
        ),
    ]
