# Generated by Django 3.2.7 on 2021-10-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='estado_departamento',
            field=models.BooleanField(default=True, verbose_name='Esta disponible'),
        ),
    ]
