# Generated by Django 3.2.7 on 2021-09-29 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0002_alter_departamento_imagen_departamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='imagen_departamento',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
