# Generated by Django 3.2.7 on 2021-10-10 01:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0003_auto_20211007_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='id_zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crudModelos.zona'),
        ),
        migrations.AlterField(
            model_name='departamento',
            name='is_transporte',
            field=models.BooleanField(choices=[(True, 'Si'), (False, 'No')], default=True, null=True),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='is_tour',
            field=models.BooleanField(default=False),
        ),
    ]
