# Generated by Django 3.2.7 on 2021-11-02 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0003_reserva_por_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='fecha_reserva',
            field=models.DateField(auto_now=True),
        ),
    ]
