# Generated by Django 3.2.7 on 2021-11-04 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0004_reserva_fecha_reserva'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='is_pago_tour',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='reserva',
            name='is_pago_transporte',
            field=models.BooleanField(default=False),
        ),
    ]
