# Generated by Django 3.2.7 on 2021-10-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0004_auto_20211010_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='valor_reserva_departamento',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_tour',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reserva',
            name='valor_transporte',
            field=models.IntegerField(default=0),
        ),
    ]
