# Generated by Django 3.2.7 on 2021-10-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudModelos', '0005_alter_reserva_id_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserva',
            old_name='is_primerPago',
            new_name='is_pago_anticipo',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='is_segundoPago',
            new_name='is_pago_checkin',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='is_tercerPago',
            new_name='is_pago_checkout',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='primer_pago_anticipo',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='segundo_pago_checkin',
        ),
        migrations.AlterField(
            model_name='reserva',
            name='check_in',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='check_out',
            field=models.DateField(),
        ),
    ]
